### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by li-changyu** [realsee-developer/vreo#15]
https://github.com/realsee-developer/vreo/blob/8a7f0cba7c7eecea0a224dbb611b07ad32e2395b/stylesheets/default.css#L434-L438

项目里的样式类名没有加限定约束，升级项目的时候发现样式类名和 `dnalogel ` 仓库的类名重复了。

**Comment by solome** [comment]
直接找 lirui 更改下类名发个新版本吧、
